Script started on Sun 26 Aug 2018 08:15:44 PM CDT
]0;carmella@carmella-Inspiron-N5110: ~[01;32mcarmella@carmella-Inspiron-N5110[00m:[01;34m~[00m$ man man
[?1049h[?1h=MAN(1)                        Manual pager utils                        MAN(1)[m
[m
[1mNAME[0m[m
       man - an interface to the on-line reference manuals[m
[m
[1mSYNOPSIS[0m[m
       [1mman[0m  [[1m-C[0m  [4mfile[24m]  [[1m-d[0m]  [[1m-D[0m]  [[1m--warnings[0m[=[4mwarnings[24m]]  [[1m-R[0m [4mencoding[24m] [[1m-L[0m[m
       [4mlocale[24m] [[1m-m[0m [4msystem[24m[,...]] [[1m-M[0m [4mpath[24m] [[1m-S[0m [4mlist[24m]  [[1m-e[0m  [4mextension[24m]  [[1m-i[0m|[1m-I[0m][m
       [[1m--regex[0m|[1m--wildcard[0m]   [[1m--names-only[0m]  [[1m-a[0m]  [[1m-u[0m]  [[1m--no-subpages[0m]  [[1m-P[0m[m
       [4mpager[24m] [[1m-r[0m [4mprompt[24m] [[1m-7[0m] [[1m-E[0m [4mencoding[24m] [[1m--no-hyphenation[0m] [[1m--no-justifi‐[0m[m
       [1mcation[0m]  [[1m-p[0m  [4mstring[24m]  [[1m-t[0m]  [[1m-T[0m[[4mdevice[24m]]  [[1m-H[0m[[4mbrowser[24m]] [[1m-X[0m[[4mdpi[24m]] [[1m-Z[0m][m
       [[[4msection[24m] [4mpage[24m ...] ...[m
       [1mman[0m [1m-k[0m [[4mapropos[24m [4moptions[24m] [4mregexp[24m ...[m
       [1mman[0m [1m-K[0m [[1m-w[0m|[1m-W[0m] [[1m-S[0m [4mlist[24m] [[1m-i[0m|[1m-I[0m] [[4m--regex[24m] [[4msection[24m] [4mterm[24m ...[m
       [1mman[0m [1m-f[0m [[4mwhatis[24m [4moptions[24m] [4mpage[24m ...[m
       [1mman[0m [1m-l[0m [[1m-C[0m [4mfile[24m] [[1m-d[0m] [[1m-D[0m] [[1m--warnings[0m[=[4mwarnings[24m]]  [[1m-R[0m  [4mencoding[24m]  [[1m-L[0m[m
       [4mlocale[24m]  [[1m-P[0m  [4mpager[24m]  [[1m-r[0m  [4mprompt[24m]  [[1m-7[0m] [[1m-E[0m [4mencoding[24m] [[1m-p[0m [4mstring[24m] [[1m-t[0m][m
       [[1m-T[0m[[4mdevice[24m]] [[1m-H[0m[[4mbrowser[24m]] [[1m-X[0m[[4mdpi[24m]] [[1m-Z[0m] [4mfile[24m ...[m
       [1mman[0m [1m-w[0m|[1m-W[0m [[1m-C[0m [4mfile[24m] [[1m-d[0m] [[1m-D[0m] [4mpage[24m ...[m
       [1mman[0m [1m-c[0m [[1m-C[0m [4mfile[24m] [[1m-d[0m] [[1m-D[0m] [4mpage[24m ...[m
       [1mman[0m [[1m-?V[0m][m
[m
[1mDESCRIPTION[0m[m
[7m Manual page man(1) line 1 (press h for help or q to quit)[27m[K[K       [1mman[0m is the system's manual pager.  Each [4mpage[24m argument given to  [1mman[0m  is[m
[7m Manual page man(1) line 2 (press h for help or q to quit)[27m[K[K[?1l>[?1049l]0;carmella@carmella-Inspiron-N5110: ~[01;32mcarmella@carmella-Inspiron-N5110[00m:[01;34m~[00m$ ls
[0m[01;34mbower_components[0m  [01;34mDownloads[0m            [01;34mMusic[0m             [01;34mPublic[0m     [01;34mVideos[0m
commands.script   examples.desktop     npm-debug.log     [01;34msnap[0m
[01;34mDesktop[0m           [01;34mgitkraken[0m            [01;34moperatingSystems[0m  [01;34mSteam[0m
[01;34mDocuments[0m         [01;31mgitkraken-amd64.deb[0m  [01;34mPictures[0m          [01;34mTemplates[0m
]0;carmella@carmella-Inspiron-N5110: ~[01;32mcarmella@carmella-Inspiron-N5110[00m:[01;34m~[00m$ mkdir proj1
]0;carmella@carmella-Inspiron-N5110: ~[01;32mcarmella@carmella-Inspiron-N5110[00m:[01;34m~[00m$ cd proj1/
]0;carmella@carmella-Inspiron-N5110: ~/proj1[01;32mcarmella@carmella-Inspiron-N5110[00m:[01;34m~/proj1[00m$ touch proj1
]0;carmella@carmella-Inspiron-N5110: ~/proj1[01;32mcarmella@carmella-Inspiron-N5110[00m:[01;34m~/proj1[00m$ rm[K[Kch[Khmod 664 prk[Kob[Kj1
]0;carmella@carmella-Inspiron-N5110: ~/proj1[01;32mcarmella@carmella-Inspiron-N5110[00m:[01;34m~/proj1[00m$ mo[Kv proj1 ~/proj1
mv: 'proj1' and '/home/carmella/proj1/proj1' are the same file
]0;carmella@carmella-Inspiron-N5110: ~/proj1[01;32mcarmella@carmella-Inspiron-N5110[00m:[01;34m~/proj1[00m$ ls proj1 ![K~/rpo[K[K[Kproj1
proj1

/home/carmella/proj1:
proj1
]0;carmella@carmella-Inspiron-N5110: ~/proj1[01;32mcarmella@carmella-Inspiron-N5110[00m:[01;34m~/proj1[00m$ ls
proj1
]0;carmella@carmella-Inspiron-N5110: ~/proj1[01;32mcarmella@carmella-Inspiron-N5110[00m:[01;34m~/proj1[00m$ mv [r[K[Kproj1 ./
mv: 'proj1' and './proj1' are the same file
]0;carmella@carmella-Inspiron-N5110: ~/proj1[01;32mcarmella@carmella-Inspiron-N5110[00m:[01;34m~/proj1[00m$ mv proj1 ~/S[KDou[Kcuments.orih[K[K[K[Ko[Kproj1
]0;carmella@carmella-Inspiron-N5110: ~/proj1[01;32mcarmella@carmella-Inspiron-N5110[00m:[01;34m~/proj1[00m$ cd ..
]0;carmella@carmella-Inspiron-N5110: ~[01;32mcarmella@carmella-Inspiron-N5110[00m:[01;34m~[00m$ rm[K[Krmdir prj[Koj1
]0;carmella@carmella-Inspiron-N5110: ~[01;32mcarmella@carmella-Inspiron-N5110[00m:[01;34m~[00m$ c[Ktp[Kop
[?1h=[?25l[H[2J(B[mtop - 20:19:09 up  4:44,  1 user,  load average: 0.29, 0.36, 0.43(B[m[39;49m(B[m[39;49m[K
Tasks:(B[m[39;49m[1m 218 (B[m[39;49mtotal,(B[m[39;49m[1m   1 (B[m[39;49mrunning,(B[m[39;49m[1m 163 (B[m[39;49msleeping,(B[m[39;49m[1m   0 (B[m[39;49mstopped,(B[m[39;49m[1m   0 (B[m[39;49mzombie(B[m[39;49m(B[m[39;49m[K
%Cpu(s):(B[m[39;49m[1m  1.2 (B[m[39;49mus,(B[m[39;49m[1m  0.5 (B[m[39;49msy,(B[m[39;49m[1m  0.0 (B[m[39;49mni,(B[m[39;49m[1m 97.8 (B[m[39;49mid,(B[m[39;49m[1m  0.5 (B[m[39;49mwa,(B[m[39;49m[1m  0.0 (B[m[39;49mhi,(B[m[39;49m[1m  0.0 (B[m[39;49msi,(B[m[39;49m[1m  0.0 (B[m[39;49mst(B[m[39;49m(B[m[39;49m[K
KiB Mem :(B[m[39;49m[1m  6007784 (B[m[39;49mtotal,(B[m[39;49m[1m  1212036 (B[m[39;49mfree,(B[m[39;49m[1m  2054552 (B[m[39;49mused,(B[m[39;49m[1m  2741196 (B[m[39;49mbuff/cache(B[m[39;49m(B[m[39;49m[K
KiB Swap:(B[m[39;49m[1m  6193148 (B[m[39;49mtotal,(B[m[39;49m[1m  6193148 (B[m[39;49mfree,(B[m[39;49m[1m        0 (B[m[39;49mused.(B[m[39;49m[1m  3390612 (B[m[39;49mavail Mem (B[m[39;49m(B[m[39;49m[K
[K
[7m  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     (B[m[39;49m[K
(B[m 1134 root      20   0  381720  96076  50396 S   6.2  1.6   1:33.88 Xorg        (B[m[39;49m[K
(B[m 3236 carmella  20   0 1230600 108440  60808 S   6.2  1.8   2:08.08 compiz      (B[m[39;49m[K
(B[m 5457 carmella  20   0 1676716 294008 134004 S   6.2  4.9   0:30.57 atom        (B[m[39;49m[K
(B[m[1m 7595 carmella  20   0   41800   3692   3104 R   6.2  0.1   0:00.01 top         (B[m[39;49m[K
(B[m    1 root      20   0  185324   5884   3992 S   0.0  0.1   0:03.14 systemd     (B[m[39;49m[K
(B[m    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd    (B[m[39;49m[K
(B[m    4 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 kworker/0:+ (B[m[39;49m[K
(B[m    6 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 mm_percpu_+ (B[m[39;49m[K
(B[m    7 root      20   0       0      0      0 S   0.0  0.0   0:00.01 ksoftirqd/0 (B[m[39;49m[K
(B[m    8 root      20   0       0      0      0 I   0.0  0.0   0:03.93 rcu_sched   (B[m[39;49m[K
(B[m    9 root      20   0       0      0      0 I   0.0  0.0   0:00.00 rcu_bh      (B[m[39;49m[K
(B[m   10 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 migration/0 (B[m[39;49m[K
(B[m   11 root      rt   0       0      0      0 S   0.0  0.0   0:00.06 watchdog/0  (B[m[39;49m[K
(B[m   12 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/0     (B[m[39;49m[K
(B[m   13 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/1     (B[m[39;49m[K
(B[m   14 root      rt   0       0      0      0 S   0.0  0.0   0:00.06 watchdog/1  (B[m[39;49m[K
(B[m   15 root      rt   0       0      0      0 S   0.0  0.0   0:00.01 migration/1 (B[m[39;49m[K[?25l[H(B[mtop - 20:19:11 up  4:44,  1 user,  load average: 0.26, 0.35, 0.42(B[m[39;49m(B[m[39;49m[K
Tasks:(B[m[39;49m[1m 218 (B[m[39;49mtotal,(B[m[39;49m[1m   1 (B[m[39;49mrunning,(B[m[39;49m[1m 163 (B[m[39;49msleeping,(B[m[39;49m[1m   0 (B[m[39;49mstopped,(B[m[39;49m[1m   0 (B[m[39;49mzombie(B[m[39;49m(B[m[39;49m[K
%Cpu(s):(B[m[39;49m[1m  2.3 (B[m[39;49mus,(B[m[39;49m[1m  0.4 (B[m[39;49msy,(B[m[39;49m[1m  0.0 (B[m[39;49mni,(B[m[39;49m[1m 97.2 (B[m[39;49mid,(B[m[39;49m[1m  0.1 (B[m[39;49mwa,(B[m[39;49m[1m  0.0 (B[m[39;49mhi,(B[m[39;49m[1m  0.0 (B[m[39;49msi,(B[m[39;49m[1m  0.0 (B[m[39;49mst(B[m[39;49m(B[m[39;49m[K
KiB Mem :(B[m[39;49m[1m  6007784 (B[m[39;49mtotal,(B[m[39;49m[1m  1209876 (B[m[39;49mfree,(B[m[39;49m[1m  2056672 (B[m[39;49mused,(B[m[39;49m[1m  2741236 (B[m[39;49mbuff/cache(B[m[39;49m(B[m[39;49m[K
KiB Swap:(B[m[39;49m[1m  6193148 (B[m[39;49mtotal,(B[m[39;49m[1m  6193148 (B[m[39;49mfree,(B[m[39;49m[1m        0 (B[m[39;49mused.(B[m[39;49m[1m  3388456 (B[m[39;49mavail Mem (B[m[39;49m(B[m[39;49m[K
[K
[7m  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     (B[m[39;49m[K
(B[m 5457 carmella  20   0 1676716 294036 134004 S   5.4  4.9   0:30.70 atom        (B[m[39;49m[K
(B[m 4401 carmella  20   0 9095740 492876 138116 S   1.2  8.2   3:56.60 firefox     (B[m[39;49m[K
(B[m 5196 carmella  20   0 1862776 210816 102988 S   1.2  3.5   0:45.20 Web Content (B[m[39;49m[K
(B[m 4462 carmella  20   0 2109516 328708 123568 S   0.8  5.5   1:27.30 Web Content (B[m[39;49m[K
(B[m 7153 carmella  20   0  633084  45108  28108 S   0.8  0.8   0:06.09 gnome-term+ (B[m[39;49m[K
(B[m 1134 root      20   0  381720  96076  50396 S   0.4  1.6   1:33.89 Xorg        (B[m[39;49m[K
(B[m 2818 carmella  20   0  345780   7460   5324 S   0.4  0.1   0:15.54 ibus-daemon (B[m[39;49m[K
(B[m 2879 carmella  20   0  188388   5364   5028 S   0.4  0.1   0:05.02 ibus-engin+ (B[m[39;49m[K
(B[m 3236 carmella  20   0 1230600 108440  60808 S   0.4  1.8   2:08.09 compiz      (B[m[39;49m[K
(B[m    1 root      20   0  185324   5884   3992 S   0.0  0.1   0:03.14 systemd     (B[m[39;49m[K
(B[m    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd    (B[m[39;49m[K
(B[m    4 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 kworker/0:+ (B[m[39;49m[K
(B[m    6 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 mm_percpu_+ (B[m[39;49m[K
(B[m    7 root      20   0       0      0      0 S   0.0  0.0   0:00.01 ksoftirqd/0 (B[m[39;49m[K
(B[m    8 root      20   0       0      0      0 I   0.0  0.0   0:03.93 rcu_sched   (B[m[39;49m[K
(B[m    9 root      20   0       0      0      0 I   0.0  0.0   0:00.00 rcu_bh      (B[m[39;49m[K
(B[m   10 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 migration/0 (B[m[39;49m[K[?25l[H(B[mtop - 20:19:12 up  4:44,  1 user,  load average: 0.26, 0.35, 0.42(B[m[39;49m(B[m[39;49m[K
Tasks:(B[m[39;49m[1m 218 (B[m[39;49mtotal,(B[m[39;49m[1m   1 (B[m[39;49mrunning,(B[m[39;49m[1m 163 (B[m[39;49msleeping,(B[m[39;49m[1m   0 (B[m[39;49mstopped,(B[m[39;49m[1m   0 (B[m[39;49mzombie(B[m[39;49m(B[m[39;49m[K
%Cpu(s):(B[m[39;49m[1m  1.9 (B[m[39;49mus,(B[m[39;49m[1m  1.9 (B[m[39;49msy,(B[m[39;49m[1m  0.0 (B[m[39;49mni,(B[m[39;49m[1m 96.1 (B[m[39;49mid,(B[m[39;49m[1m  0.0 (B[m[39;49mwa,(B[m[39;49m[1m  0.0 (B[m[39;49mhi,(B[m[39;49m[1m  0.0 (B[m[39;49msi,(B[m[39;49m[1m  0.0 (B[m[39;49mst(B[m[39;49m(B[m[39;49m[K
KiB Mem :(B[m[39;49m[1m  6007784 (B[m[39;49mtotal,(B[m[39;49m[1m  1209876 (B[m[39;49mfree,(B[m[39;49m[1m  2055632 (B[m[39;49mused,(B[m[39;49m[1m  2742276 (B[m[39;49mbuff/cache(B[m[39;49m(B[m[39;49m[K
KiB Swap:(B[m[39;49m[1m  6193148 (B[m[39;49mtotal,(B[m[39;49m[1m  6193148 (B[m[39;49mfree,(B[m[39;49m[1m        0 (B[m[39;49mused.(B[m[39;49m[1m  3388460 (B[m[39;49mavail Mem (B[m[39;49m(B[m[39;49m[K
[K
[7m  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     (B[m[39;49m[K
(B[m 5506 carmella  20   0 9817748 293956 132488 S   5.1  4.9   0:21.50 atom        (B[m[39;49m[K
(B[m[1m 7595 carmella  20   0   41800   3692   3104 R   5.1  0.1   0:00.03 top         (B[m[39;49m[K
(B[m    8 root      20   0       0      0      0 I   2.6  0.0   0:03.94 rcu_sched   (B[m[39;49m[K
(B[m 2879 carmella  20   0  188388   5364   5028 S   2.6  0.1   0:05.03 ibus-engin+ (B[m[39;49m[K
(B[m 5457 carmella  20   0 1676716 294036 134004 S   2.6  4.9   0:30.71 atom        (B[m[39;49m[K
(B[m    1 root      20   0  185324   5884   3992 S   0.0  0.1   0:03.14 systemd     (B[m[39;49m[K
(B[m    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd    (B[m[39;49m[K
(B[m    4 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 kworker/0:+ (B[m[39;49m[K
(B[m    6 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 mm_percpu_+ (B[m[39;49m[K
(B[m    7 root      20   0       0      0      0 S   0.0  0.0   0:00.01 ksoftirqd/0 (B[m[39;49m[K
(B[m    9 root      20   0       0      0      0 I   0.0  0.0   0:00.00 rcu_bh      (B[m[39;49m[K
(B[m   10 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 migration/0 (B[m[39;49m[K
(B[m   11 root      rt   0       0      0      0 S   0.0  0.0   0:00.06 watchdog/0  (B[m[39;49m[K
(B[m   12 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/0     (B[m[39;49m[K
(B[m   13 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/1     (B[m[39;49m[K
(B[m   14 root      rt   0       0      0      0 S   0.0  0.0   0:00.06 watchdog/1  (B[m[39;49m[K
(B[m   15 root      rt   0       0      0      0 S   0.0  0.0   0:00.01 migration/1 (B[m[39;49m[K[?25l[H(B[mtop - 20:19:12 up  4:44,  1 user,  load average: 0.26, 0.35, 0.42(B[m[39;49m(B[m[39;49m[K
Tasks:(B[m[39;49m[1m 218 (B[m[39;49mtotal,(B[m[39;49m[1m   1 (B[m[39;49mrunning,(B[m[39;49m[1m 163 (B[m[39;49msleeping,(B[m[39;49m[1m   0 (B[m[39;49mstopped,(B[m[39;49m[1m   0 (B[m[39;49mzombie(B[m[39;49m(B[m[39;49m[K
%Cpu(s):(B[m[39;49m[1m  3.5 (B[m[39;49mus,(B[m[39;49m[1m  0.9 (B[m[39;49msy,(B[m[39;49m[1m  0.0 (B[m[39;49mni,(B[m[39;49m[1m 95.7 (B[m[39;49mid,(B[m[39;49m[1m  0.0 (B[m[39;49mwa,(B[m[39;49m[1m  0.0 (B[m[39;49mhi,(B[m[39;49m[1m  0.0 (B[m[39;49msi,(B[m[39;49m[1m  0.0 (B[m[39;49mst(B[m[39;49m(B[m[39;49m[K
KiB Mem :(B[m[39;49m[1m  6007784 (B[m[39;49mtotal,(B[m[39;49m[1m  1210468 (B[m[39;49mfree,(B[m[39;49m[1m  2055036 (B[m[39;49mused,(B[m[39;49m[1m  2742280 (B[m[39;49mbuff/cache(B[m[39;49m(B[m[39;49m[K
KiB Swap:(B[m[39;49m[1m  6193148 (B[m[39;49mtotal,(B[m[39;49m[1m  6193148 (B[m[39;49mfree,(B[m[39;49m[1m        0 (B[m[39;49mused.(B[m[39;49m[1m  3389056 (B[m[39;49mavail Mem (B[m[39;49m(B[m[39;49m[K
[K
[7m  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     (B[m[39;49m[K
(B[m 2818 carmella  20   0  345780   7460   5324 S   3.4  0.1   0:15.55 ibus-daemon (B[m[39;49m[K
(B[m 2958 carmella  20   0  871480  46644  30208 S   3.4  0.8   0:00.69 unity-sett+ (B[m[39;49m[K
(B[m 4677 carmella  20   0 2101004 225236 109224 S   3.4  3.7   1:18.65 Web Content (B[m[39;49m[K
(B[m 5506 carmella  20   0 9825944 294120 132488 S   3.4  4.9   0:21.51 atom        (B[m[39;49m[K
(B[m 7153 carmella  20   0  633084  45108  28108 S   3.4  0.8   0:06.10 gnome-term+ (B[m[39;49m[K
(B[m[1m 7595 carmella  20   0   41800   3692   3104 R   3.4  0.1   0:00.04 top         (B[m[39;49m[K
(B[m    1 root      20   0  185324   5884   3992 S   0.0  0.1   0:03.14 systemd     (B[m[39;49m[K
(B[m    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd    (B[m[39;49m[K
(B[m    4 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 kworker/0:+ (B[m[39;49m[K
(B[m    6 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 mm_percpu_+ (B[m[39;49m[K
(B[m    7 root      20   0       0      0      0 S   0.0  0.0   0:00.01 ksoftirqd/0 (B[m[39;49m[K
(B[m    8 root      20   0       0      0      0 I   0.0  0.0   0:03.94 rcu_sched   (B[m[39;49m[K
(B[m    9 root      20   0       0      0      0 I   0.0  0.0   0:00.00 rcu_bh      (B[m[39;49m[K
(B[m   10 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 migration/0 (B[m[39;49m[K
(B[m   11 root      rt   0       0      0      0 S   0.0  0.0   0:00.06 watchdog/0  (B[m[39;49m[K
(B[m   12 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/0     (B[m[39;49m[K
(B[m   13 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/1     (B[m[39;49m[K[?25l[H(B[mtop - 20:19:12 up  4:44,  1 user,  load average: 0.26, 0.35, 0.42(B[m[39;49m(B[m[39;49m[K
Tasks:(B[m[39;49m[1m 218 (B[m[39;49mtotal,(B[m[39;49m[1m   1 (B[m[39;49mrunning,(B[m[39;49m[1m 163 (B[m[39;49msleeping,(B[m[39;49m[1m   0 (B[m[39;49mstopped,(B[m[39;49m[1m   0 (B[m[39;49mzombie(B[m[39;49m(B[m[39;49m[K
%Cpu(s):(B[m[39;49m[1m  5.3 (B[m[39;49mus,(B[m[39;49m[1m  0.0 (B[m[39;49msy,(B[m[39;49m[1m  0.0 (B[m[39;49mni,(B[m[39;49m[1m 94.7 (B[m[39;49mid,(B[m[39;49m[1m  0.0 (B[m[39;49mwa,(B[m[39;49m[1m  0.0 (B[m[39;49mhi,(B[m[39;49m[1m  0.0 (B[m[39;49msi,(B[m[39;49m[1m  0.0 (B[m[39;49mst(B[m[39;49m(B[m[39;49m[K
KiB Mem :(B[m[39;49m[1m  6007784 (B[m[39;49mtotal,(B[m[39;49m[1m  1210672 (B[m[39;49mfree,(B[m[39;49m[1m  2054828 (B[m[39;49mused,(B[m[39;49m[1m  2742284 (B[m[39;49mbuff/cache(B[m[39;49m(B[m[39;49m[K
KiB Swap:(B[m[39;49m[1m  6193148 (B[m[39;49mtotal,(B[m[39;49m[1m  6193148 (B[m[39;49mfree,(B[m[39;49m[1m        0 (B[m[39;49mused.(B[m[39;49m[1m  3389260 (B[m[39;49mavail Mem (B[m[39;49m(B[m[39;49m[K
[K
[7m  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     (B[m[39;49m[K
(B[m 7153 carmella  20   0  633084  45108  28108 S   4.2  0.8   0:06.11 gnome-term+ (B[m[39;49m[K
(B[m    1 root      20   0  185324   5884   3992 S   0.0  0.1   0:03.14 systemd     (B[m[39;49m[K
(B[m    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd    (B[m[39;49m[K
(B[m    4 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 kworker/0:+ (B[m[39;49m[K
(B[m    6 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 mm_percpu_+ (B[m[39;49m[K
(B[m    7 root      20   0       0      0      0 S   0.0  0.0   0:00.01 ksoftirqd/0 (B[m[39;49m[K
(B[m    8 root      20   0       0      0      0 I   0.0  0.0   0:03.94 rcu_sched   (B[m[39;49m[K
(B[m    9 root      20   0       0      0      0 I   0.0  0.0   0:00.00 rcu_bh      (B[m[39;49m[K
(B[m   10 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 migration/0 (B[m[39;49m[K
(B[m   11 root      rt   0       0      0      0 S   0.0  0.0   0:00.06 watchdog/0  (B[m[39;49m[K
(B[m   12 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/0     (B[m[39;49m[K
(B[m   13 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/1     (B[m[39;49m[K
(B[m   14 root      rt   0       0      0      0 S   0.0  0.0   0:00.06 watchdog/1  (B[m[39;49m[K
(B[m   15 root      rt   0       0      0      0 S   0.0  0.0   0:00.01 migration/1 (B[m[39;49m[K
(B[m   16 root      20   0       0      0      0 S   0.0  0.0   0:00.03 ksoftirqd/1 (B[m[39;49m[K
(B[m   18 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 kworker/1:+ (B[m[39;49m[K
(B[m   19 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/2     (B[m[39;49m[K[?25l[H(B[mtop - 20:19:13 up  4:44,  1 user,  load average: 0.26, 0.35, 0.42(B[m[39;49m(B[m[39;49m[K
Tasks:(B[m[39;49m[1m 218 (B[m[39;49mtotal,(B[m[39;49m[1m   1 (B[m[39;49mrunning,(B[m[39;49m[1m 163 (B[m[39;49msleeping,(B[m[39;49m[1m   0 (B[m[39;49mstopped,(B[m[39;49m[1m   0 (B[m[39;49mzombie(B[m[39;49m(B[m[39;49m[K
%Cpu(s):(B[m[39;49m[1m  4.7 (B[m[39;49mus,(B[m[39;49m[1m  3.1 (B[m[39;49msy,(B[m[39;49m[1m  0.0 (B[m[39;49mni,(B[m[39;49m[1m 92.2 (B[m[39;49mid,(B[m[39;49m[1m  0.0 (B[m[39;49mwa,(B[m[39;49m[1m  0.0 (B[m[39;49mhi,(B[m[39;49m[1m  0.0 (B[m[39;49msi,(B[m[39;49m[1m  0.0 (B[m[39;49mst(B[m[39;49m(B[m[39;49m[K
KiB Mem :(B[m[39;49m[1m  6007784 (B[m[39;49mtotal,(B[m[39;49m[1m  1210672 (B[m[39;49mfree,(B[m[39;49m[1m  2054828 (B[m[39;49mused,(B[m[39;49m[1m  2742284 (B[m[39;49mbuff/cache(B[m[39;49m(B[m[39;49m[K
KiB Swap:(B[m[39;49m[1m  6193148 (B[m[39;49mtotal,(B[m[39;49m[1m  6193148 (B[m[39;49mfree,(B[m[39;49m[1m        0 (B[m[39;49mused.(B[m[39;49m[1m  3389260 (B[m[39;49mavail Mem (B[m[39;49m(B[m[39;49m[K
[K
[7m  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     (B[m[39;49m[K
(B[m  972 message+  20   0   44312   5236   3524 S   6.2  0.1   0:07.07 dbus-daemon (B[m[39;49m[K
(B[m  988 root      20   0  662876  17308  13768 S   6.2  0.3   0:10.66 NetworkMan+ (B[m[39;49m[K
(B[m 1134 root      20   0  381704  96092  50412 S   6.2  1.6   1:33.91 Xorg        (B[m[39;49m[K
(B[m 5438 root      20   0       0      0      0 I   6.2  0.0   0:00.98 kworker/u8+ (B[m[39;49m[K
(B[m 5457 carmella  20   0 1676716 294036 134004 S   6.2  4.9   0:30.72 atom        (B[m[39;49m[K
(B[m    1 root      20   0  185324   5884   3992 S   0.0  0.1   0:03.14 systemd     (B[m[39;49m[K
(B[m    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd    (B[m[39;49m[K
(B[m    4 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 kworker/0:+ (B[m[39;49m[K
(B[m    6 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 mm_percpu_+ (B[m[39;49m[K
(B[m    7 root      20   0       0      0      0 S   0.0  0.0   0:00.01 ksoftirqd/0 (B[m[39;49m[K
(B[m    8 root      20   0       0      0      0 I   0.0  0.0   0:03.94 rcu_sched   (B[m[39;49m[K
(B[m    9 root      20   0       0      0      0 I   0.0  0.0   0:00.00 rcu_bh      (B[m[39;49m[K
(B[m   10 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 migration/0 (B[m[39;49m[K
(B[m   11 root      rt   0       0      0      0 S   0.0  0.0   0:00.06 watchdog/0  (B[m[39;49m[K
(B[m   12 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/0     (B[m[39;49m[K
(B[m   13 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/1     (B[m[39;49m[K
(B[m   14 root      rt   0       0      0      0 S   0.0  0.0   0:00.06 watchdog/1  (B[m[39;49m[K[?25l[H(B[mtop - 20:19:13 up  4:44,  1 user,  load average: 0.26, 0.35, 0.42(B[m[39;49m(B[m[39;49m[K
Tasks:(B[m[39;49m[1m 218 (B[m[39;49mtotal,(B[m[39;49m[1m   1 (B[m[39;49mrunning,(B[m[39;49m[1m 163 (B[m[39;49msleeping,(B[m[39;49m[1m   0 (B[m[39;49mstopped,(B[m[39;49m[1m   0 (B[m[39;49mzombie(B[m[39;49m(B[m[39;49m[K
%Cpu(s):(B[m[39;49m[1m  3.7 (B[m[39;49mus,(B[m[39;49m[1m  2.4 (B[m[39;49msy,(B[m[39;49m[1m  0.0 (B[m[39;49mni,(B[m[39;49m[1m 93.9 (B[m[39;49mid,(B[m[39;49m[1m  0.0 (B[m[39;49mwa,(B[m[39;49m[1m  0.0 (B[m[39;49mhi,(B[m[39;49m[1m  0.0 (B[m[39;49msi,(B[m[39;49m[1m  0.0 (B[m[39;49mst(B[m[39;49m(B[m[39;49m[K
KiB Mem :(B[m[39;49m[1m  6007784 (B[m[39;49mtotal,(B[m[39;49m[1m  1210548 (B[m[39;49mfree,(B[m[39;49m[1m  2054856 (B[m[39;49mused,(B[m[39;49m[1m  2742380 (B[m[39;49mbuff/cache(B[m[39;49m(B[m[39;49m[K
KiB Swap:(B[m[39;49m[1m  6193148 (B[m[39;49mtotal,(B[m[39;49m[1m  6193148 (B[m[39;49mfree,(B[m[39;49m[1m        0 (B[m[39;49mused.(B[m[39;49m[1m  3389136 (B[m[39;49mavail Mem (B[m[39;49m(B[m[39;49m[K
[K
[7m  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     (B[m[39;49m[K
(B[m[1m 7595 carmella  20   0   41800   3692   3104 R   5.0  0.1   0:00.07 top         (B[m[39;49m[K
(B[m    1 root      20   0  185324   5884   3992 S   0.0  0.1   0:03.14 systemd     (B[m[39;49m[K
(B[m    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd    (B[m[39;49m[K
(B[m    4 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 kworker/0:+ (B[m[39;49m[K
(B[m    6 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 mm_percpu_+ (B[m[39;49m[K
(B[m    7 root      20   0       0      0      0 S   0.0  0.0   0:00.01 ksoftirqd/0 (B[m[39;49m[K
(B[m    8 root      20   0       0      0      0 I   0.0  0.0   0:03.94 rcu_sched   (B[m[39;49m[K
(B[m    9 root      20   0       0      0      0 I   0.0  0.0   0:00.00 rcu_bh      (B[m[39;49m[K
(B[m   10 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 migration/0 (B[m[39;49m[K
(B[m   11 root      rt   0       0      0      0 S   0.0  0.0   0:00.06 watchdog/0  (B[m[39;49m[K
(B[m   12 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/0     (B[m[39;49m[K
(B[m   13 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/1     (B[m[39;49m[K
(B[m   14 root      rt   0       0      0      0 S   0.0  0.0   0:00.06 watchdog/1  (B[m[39;49m[K
(B[m   15 root      rt   0       0      0      0 S   0.0  0.0   0:00.01 migration/1 (B[m[39;49m[K
(B[m   16 root      20   0       0      0      0 S   0.0  0.0   0:00.03 ksoftirqd/1 (B[m[39;49m[K
(B[m   18 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 kworker/1:+ (B[m[39;49m[K
(B[m   19 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/2     (B[m[39;49m[K[?25l[H(B[mtop - 20:19:13 up  4:44,  1 user,  load average: 0.26, 0.35, 0.42(B[m[39;49m(B[m[39;49m[K
Tasks:(B[m[39;49m[1m 218 (B[m[39;49mtotal,(B[m[39;49m[1m   1 (B[m[39;49mrunning,(B[m[39;49m[1m 163 (B[m[39;49msleeping,(B[m[39;49m[1m   0 (B[m[39;49mstopped,(B[m[39;49m[1m   0 (B[m[39;49mzombie(B[m[39;49m(B[m[39;49m[K
%Cpu(s):(B[m[39;49m[1m 50.0 (B[m[39;49mus,(B[m[39;49m[1m  0.0 (B[m[39;49msy,(B[m[39;49m[1m  0.0 (B[m[39;49mni,(B[m[39;49m[1m 50.0 (B[m[39;49mid,(B[m[39;49m[1m  0.0 (B[m[39;49mwa,(B[m[39;49m[1m  0.0 (B[m[39;49mhi,(B[m[39;49m[1m  0.0 (B[m[39;49msi,(B[m[39;49m[1m  0.0 (B[m[39;49mst(B[m[39;49m(B[m[39;49m[K
KiB Mem :(B[m[39;49m[1m  6007784 (B[m[39;49mtotal,(B[m[39;49m[1m  1210548 (B[m[39;49mfree,(B[m[39;49m[1m  2054856 (B[m[39;49mused,(B[m[39;49m[1m  2742380 (B[m[39;49mbuff/cache(B[m[39;49m(B[m[39;49m[K
KiB Swap:(B[m[39;49m[1m  6193148 (B[m[39;49mtotal,(B[m[39;49m[1m  6193148 (B[m[39;49mfree,(B[m[39;49m[1m        0 (B[m[39;49mused.(B[m[39;49m[1m  3389136 (B[m[39;49mavail Mem (B[m[39;49m(B[m[39;49m[K
[K
[7m  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     (B[m[39;49m[K
(B[m    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd    (B[m[39;49m[K
(B[m    4 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 kworker/0:+ (B[m[39;49m[K
(B[m    6 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 mm_percpu_+ (B[m[39;49m[K
(B[m    7 root      20   0       0      0      0 S   0.0  0.0   0:00.01 ksoftirqd/0 (B[m[39;49m[K
(B[m    8 root      20   0       0      0      0 I   0.0  0.0   0:03.94 rcu_sched   (B[m[39;49m[K
(B[m    9 root      20   0       0      0      0 I   0.0  0.0   0:00.00 rcu_bh      (B[m[39;49m[K
(B[m   10 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 migration/0 (B[m[39;49m[K
(B[m   11 root      rt   0       0      0      0 S   0.0  0.0   0:00.06 watchdog/0  (B[m[39;49m[K
(B[m   12 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/0     (B[m[39;49m[K
(B[m   13 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/1     (B[m[39;49m[K
(B[m   14 root      rt   0       0      0      0 S   0.0  0.0   0:00.06 watchdog/1  (B[m[39;49m[K
(B[m   15 root      rt   0       0      0      0 S   0.0  0.0   0:00.01 migration/1 (B[m[39;49m[K
(B[m   16 root      20   0       0      0      0 S   0.0  0.0   0:00.03 ksoftirqd/1 (B[m[39;49m[K
(B[m   18 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 kworker/1:+ (B[m[39;49m[K
(B[m   19 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/2     (B[m[39;49m[K
(B[m   20 root      rt   0       0      0      0 S   0.0  0.0   0:00.06 watchdog/2  (B[m[39;49m[K
(B[m   21 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 migration/2 (B[m[39;49m[K[?25l[H(B[mtop - 20:19:13 up  4:44,  1 user,  load average: 0.26, 0.35, 0.42(B[m[39;49m(B[m[39;49m[K
Tasks:(B[m[39;49m[1m 218 (B[m[39;49mtotal,(B[m[39;49m[1m   1 (B[m[39;49mrunning,(B[m[39;49m[1m 163 (B[m[39;49msleeping,(B[m[39;49m[1m   0 (B[m[39;49mstopped,(B[m[39;49m[1m   0 (B[m[39;49mzombie(B[m[39;49m(B[m[39;49m[K
%Cpu(s):(B[m[39;49m[1m  3.3 (B[m[39;49mus,(B[m[39;49m[1m  2.2 (B[m[39;49msy,(B[m[39;49m[1m  0.0 (B[m[39;49mni,(B[m[39;49m[1m 94.4 (B[m[39;49mid,(B[m[39;49m[1m  0.0 (B[m[39;49mwa,(B[m[39;49m[1m  0.0 (B[m[39;49mhi,(B[m[39;49m[1m  0.0 (B[m[39;49msi,(B[m[39;49m[1m  0.0 (B[m[39;49mst(B[m[39;49m(B[m[39;49m[K
KiB Mem :(B[m[39;49m[1m  6007784 (B[m[39;49mtotal,(B[m[39;49m[1m  1210672 (B[m[39;49mfree,(B[m[39;49m[1m  2054732 (B[m[39;49mused,(B[m[39;49m[1m  2742380 (B[m[39;49mbuff/cache(B[m[39;49m(B[m[39;49m[K
KiB Swap:(B[m[39;49m[1m  6193148 (B[m[39;49mtotal,(B[m[39;49m[1m  6193148 (B[m[39;49mfree,(B[m[39;49m[1m        0 (B[m[39;49mused.(B[m[39;49m[1m  3389260 (B[m[39;49mavail Mem (B[m[39;49m(B[m[39;49m[K
[K
[7m  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     (B[m[39;49m[K
(B[m 1134 root      20   0  381192  96216  50536 S   4.5  1.6   1:33.92 Xorg        (B[m[39;49m[K
(B[m 4462 carmella  20   0 2109516 328708 123568 S   4.5  5.5   1:27.31 Web Content (B[m[39;49m[K
(B[m 5506 carmella  20   0 9850532 294156 132488 S   4.5  4.9   0:21.53 atom        (B[m[39;49m[K
(B[m 7153 carmella  20   0  633084  45108  28108 S   4.5  0.8   0:06.13 gnome-term+ (B[m[39;49m[K
(B[m[1m 7595 carmella  20   0   41800   3692   3104 R   4.5  0.1   0:00.08 top         (B[m[39;49m[K
(B[m    1 root      20   0  185324   5884   3992 S   0.0  0.1   0:03.14 systemd     (B[m[39;49m[K
(B[m    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd    (B[m[39;49m[K
(B[m    4 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 kworker/0:+ (B[m[39;49m[K
(B[m    6 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 mm_percpu_+ (B[m[39;49m[K
(B[m    7 root      20   0       0      0      0 S   0.0  0.0   0:00.01 ksoftirqd/0 (B[m[39;49m[K
(B[m    8 root      20   0       0      0      0 I   0.0  0.0   0:03.94 rcu_sched   (B[m[39;49m[K
(B[m    9 root      20   0       0      0      0 I   0.0  0.0   0:00.00 rcu_bh      (B[m[39;49m[K
(B[m   10 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 migration/0 (B[m[39;49m[K
(B[m   11 root      rt   0       0      0      0 S   0.0  0.0   0:00.06 watchdog/0  (B[m[39;49m[K
(B[m   12 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/0     (B[m[39;49m[K
(B[m   13 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/1     (B[m[39;49m[K
(B[m   14 root      rt   0       0      0      0 S   0.0  0.0   0:00.06 watchdog/1  (B[m[39;49m[K[?25l[H(B[mtop - 20:19:14 up  4:44,  1 user,  load average: 0.26, 0.35, 0.42(B[m[39;49m(B[m[39;49m[K
Tasks:(B[m[39;49m[1m 218 (B[m[39;49mtotal,(B[m[39;49m[1m   1 (B[m[39;49mrunning,(B[m[39;49m[1m 163 (B[m[39;49msleeping,(B[m[39;49m[1m   0 (B[m[39;49mstopped,(B[m[39;49m[1m   0 (B[m[39;49mzombie(B[m[39;49m(B[m[39;49m[K
%Cpu(s):(B[m[39;49m[1m  0.9 (B[m[39;49mus,(B[m[39;49m[1m  1.3 (B[m[39;49msy,(B[m[39;49m[1m  0.0 (B[m[39;49mni,(B[m[39;49m[1m 97.9 (B[m[39;49mid,(B[m[39;49m[1m  0.0 (B[m[39;49mwa,(B[m[39;49m[1m  0.0 (B[m[39;49mhi,(B[m[39;49m[1m  0.0 (B[m[39;49msi,(B[m[39;49m[1m  0.0 (B[m[39;49mst(B[m[39;49m(B[m[39;49m[K
KiB Mem :(B[m[39;49m[1m  6007784 (B[m[39;49mtotal,(B[m[39;49m[1m  1210672 (B[m[39;49mfree,(B[m[39;49m[1m  2054728 (B[m[39;49mused,(B[m[39;49m[1m  2742384 (B[m[39;49mbuff/cache(B[m[39;49m(B[m[39;49m[K
KiB Swap:(B[m[39;49m[1m  6193148 (B[m[39;49mtotal,(B[m[39;49m[1m  6193148 (B[m[39;49mfree,(B[m[39;49m[1m        0 (B[m[39;49mused.(B[m[39;49m[1m  3389264 (B[m[39;49mavail Mem (B[m[39;49m(B[m[39;49m[K
[K
[7m  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     (B[m[39;49m[K
(B[m 2818 carmella  20   0  345780   7460   5324 S   1.7  0.1   0:15.57 /usr/bin/i+ (B[m[39;49m[K
(B[m 5506 carmella  20   0 9858728 294416 132488 S   1.7  4.9   0:21.54 /opt/atom/+ (B[m[39;49m[K
(B[m 7153 carmella  20   0  633084  45108  28108 S   1.7  0.8   0:06.14 /usr/lib/g+ (B[m[39;49m[K
(B[m    1 root      20   0  185324   5884   3992 S   0.0  0.1   0:03.14 /sbin/init+ (B[m[39;49m[K
(B[m    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 [kthreadd]  (B[m[39;49m[K
(B[m    4 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 [kworker/0+ (B[m[39;49m[K
(B[m    6 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 [mm_percpu+ (B[m[39;49m[K
(B[m    7 root      20   0       0      0      0 S   0.0  0.0   0:00.01 [ksoftirqd+ (B[m[39;49m[K
(B[m    8 root      20   0       0      0      0 I   0.0  0.0   0:03.94 [rcu_sched] (B[m[39;49m[K
(B[m    9 root      20   0       0      0      0 I   0.0  0.0   0:00.00 [rcu_bh]    (B[m[39;49m[K
(B[m   10 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 [migration+ (B[m[39;49m[K
(B[m   11 root      rt   0       0      0      0 S   0.0  0.0   0:00.06 [watchdog/+ (B[m[39;49m[K
(B[m   12 root      20   0       0      0      0 S   0.0  0.0   0:00.00 [cpuhp/0]   (B[m[39;49m[K
(B[m   13 root      20   0       0      0      0 S   0.0  0.0   0:00.00 [cpuhp/1]   (B[m[39;49m[K
(B[m   14 root      rt   0       0      0      0 S   0.0  0.0   0:00.06 [watchdog/+ (B[m[39;49m[K
(B[m   15 root      rt   0       0      0      0 S   0.0  0.0   0:00.01 [migration+ (B[m[39;49m[K
(B[m   16 root      20   0       0      0      0 S   0.0  0.0   0:00.03 [ksoftirqd+ (B[m[39;49m[K[?1l>[25;1H
[?12l[?25h[K]0;carmella@carmella-Inspiron-N5110: ~[01;32mcarmella@carmella-Inspiron-N5110[00m:[01;34m~[00m$ clear
[3;J[H[2J]0;carmella@carmella-Inspiron-N5110: ~[01;32mcarmella@carmella-Inspiron-N5110[00m:[01;34m~[00m$ who
carmella tty7         2018-08-26 19:23 (:0)
]0;carmella@carmella-Inspiron-N5110: ~[01;32mcarmella@carmella-Inspiron-N5110[00m:[01;34m~[00m$ nproc
4
]0;carmella@carmella-Inspiron-N5110: ~[01;32mcarmella@carmella-Inspiron-N5110[00m:[01;34m~[00m$ pwd
/home/carmella
]0;carmella@carmella-Inspiron-N5110: ~[01;32mcarmella@carmella-Inspiron-N5110[00m:[01;34m~[00m$ touch wow
]0;carmella@carmella-Inspiron-N5110: ~[01;32mcarmella@carmella-Inspiron-N5110[00m:[01;34m~[00m$ cp wow ~/Documents
]0;carmella@carmella-Inspiron-N5110: ~[01;32mcarmella@carmella-Inspiron-N5110[00m:[01;34m~[00m$ exit
exit

Script done on Sun 26 Aug 2018 08:20:15 PM CDT
